/**
 * 歌尔供应链控制塔 v7.2 — Demo主维度数据-2 (153项目 · 含工程阶段/生命周期/重大项目标签)
 */
const bgHierarchy = {
  A01:{ label:'A01 声学BG', bus:{ BU1:'A01-BU1', BU2:'A01-BU2' } },
  CEP:{ label:'CEP 消费电子BG', bus:{ BU1:'CEP-BU1', BU2:'CEP-BU2' } },
  SAC:{ label:'SAC 微电子BG', bus:{ BU1:'SAC-BU1', BU2:'SAC-BU2' } },
};

// ========== 核心项目数据（153个项目） ==========
const projects = [
  { id:'P001', name:'HW-TWS-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:15000 },
  { id:'P002', name:'HW-TWS-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:22500 },
  { id:'P003', name:'HW-TWS-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:30000 },
  { id:'P004', name:'HW-TWS-A1004', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'赵丽', volume:37500 },
  { id:'P005', name:'HW-TWS-A1005', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'陈伟', volume:45000 },
  { id:'P006', name:'HW-TWS-A1006', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'孙强', volume:15000 },
  { id:'P007', name:'HW-OHP-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'头戴耳机', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'周强', volume:6000 },
  { id:'P008', name:'HW-OHP-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'头戴耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:8000 },
  { id:'P009', name:'HW-OHP-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'头戴耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:true, pm:'郑凯', volume:10000 },
  { id:'P010', name:'HW-OHP-A1004', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'头戴耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'杨帆', volume:12000 },
  { id:'P011', name:'HW-ANC-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:6000 },
  { id:'P012', name:'HW-ANC-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:9000 },
  { id:'P013', name:'HW-ANC-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'刘燕', volume:12000 },
  { id:'P014', name:'HW-ANC-A1004', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:15000 },
  { id:'P015', name:'HW-SWT-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:9000 },
  { id:'P016', name:'HW-SWT-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'孙强', volume:3000 },
  { id:'P017', name:'HW-SWT-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:true, pm:'周强', volume:4500 },
  { id:'P018', name:'HW-SWT-A1004', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'吴芳', volume:6000 },
  { id:'P019', name:'HW-SGL-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能眼镜', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:3750 },
  { id:'P020', name:'HW-SGL-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能眼镜', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'杨帆', volume:4500 },
  { id:'P021', name:'HW-SGL-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'智能眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:1500 },
  { id:'P022', name:'HW-SBD-A1001', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'运动手环', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:11250 },
  { id:'P023', name:'HW-SBD-A1002', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'运动手环', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'刘燕', volume:15000 },
  { id:'P024', name:'HW-SBD-A1003', customer:'华为', bg:'A01', bu:'A01-BU1', productLine:'运动手环', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'赵丽', volume:18750 },
  { id:'P025', name:'HR-TWS-A1001', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:45000 },
  { id:'P026', name:'HR-TWS-A1002', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:15000 },
  { id:'P027', name:'HR-TWS-A1003', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'周强', volume:22500 },
  { id:'P028', name:'HR-SWT-A1001', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'吴芳', volume:6000 },
  { id:'P029', name:'HR-SWT-A1002', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'郑凯', volume:7500 },
  { id:'P030', name:'HR-SWT-A1003', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'杨帆', volume:9000 },
  { id:'P031', name:'HR-ANC-A1001', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:6000 },
  { id:'P032', name:'HR-ANC-A1002', customer:'荣耀', bg:'A01', bu:'A01-BU1', productLine:'降噪耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'李建国', volume:9000 },
  { id:'P033', name:'MI-TWS-A1001', customer:'小米', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:30000 },
  { id:'P034', name:'MI-TWS-A1002', customer:'小米', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:37500 },
  { id:'P035', name:'MI-TWS-A1003', customer:'小米', bg:'A01', bu:'A01-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'陈伟', volume:45000 },
  { id:'P036', name:'HW-VRH-A2001', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'VR头显', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:2500 },
  { id:'P037', name:'HW-VRH-A2002', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'周强', volume:3750 },
  { id:'P038', name:'HW-ARG-A2001', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'吴芳', volume:4000 },
  { id:'P039', name:'HW-ARG-A2002', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:5000 },
  { id:'P040', name:'HW-ARG-A2003', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'杨帆', volume:6000 },
  { id:'P041', name:'HW-MRH-A2001', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'MR头显', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:1000 },
  { id:'P042', name:'HW-MRH-A2002', customer:'华为', bg:'A01', bu:'A01-BU2', productLine:'MR头显', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:1500 },
  { id:'P043', name:'MI-VRH-A2001', customer:'小米', bg:'A01', bu:'A01-BU2', productLine:'VR头显', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:5000 },
  { id:'P044', name:'MI-VRH-A2002', customer:'小米', bg:'A01', bu:'A01-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:6250 },
  { id:'P045', name:'MI-ARG-A2001', customer:'小米', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:6000 },
  { id:'P046', name:'MI-ARG-A2002', customer:'小米', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'孙强', volume:2000 },
  { id:'P047', name:'OP-ARG-A2001', customer:'OPPO', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'周强', volume:3000 },
  { id:'P048', name:'OP-ARG-A2002', customer:'OPPO', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:4000 },
  { id:'P049', name:'OP-TWS-A2001', customer:'OPPO', bg:'A01', bu:'A01-BU2', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'郑凯', volume:37500 },
  { id:'P050', name:'OP-TWS-A2002', customer:'OPPO', bg:'A01', bu:'A01-BU2', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'杨帆', volume:45000 },
  { id:'P051', name:'VI-TWS-A2001', customer:'vivo', bg:'A01', bu:'A01-BU2', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:15000 },
  { id:'P052', name:'VI-TWS-A2002', customer:'vivo', bg:'A01', bu:'A01-BU2', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'李建国', volume:22500 },
  { id:'P053', name:'VI-SWT-A2001', customer:'vivo', bg:'A01', bu:'A01-BU2', productLine:'智能手表', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:6000 },
  { id:'P054', name:'VI-SWT-A2002', customer:'vivo', bg:'A01', bu:'A01-BU2', productLine:'智能手表', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:7500 },
  { id:'P055', name:'HR-ARG-A2001', customer:'荣耀', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:6000 },
  { id:'P056', name:'HR-ARG-A2002', customer:'荣耀', bg:'A01', bu:'A01-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'孙强', volume:2000 },
  { id:'P057', name:'GG-TWS-C1001', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'周强', volume:22500 },
  { id:'P058', name:'GG-TWS-C1002', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'吴芳', volume:30000 },
  { id:'P059', name:'GG-SWT-C1001', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:7500 },
  { id:'P060', name:'GG-SWT-C1002', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'杨帆', volume:9000 },
  { id:'P061', name:'GG-SWT-C1003', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'张明远', volume:3000 },
  { id:'P062', name:'GG-SGL-C1001', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'智能眼镜', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:2250 },
  { id:'P063', name:'GG-SGL-C1002', customer:'Google', bg:'CEP', bu:'CEP-BU1', productLine:'智能眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:true, pm:'刘燕', volume:3000 },
  { id:'P064', name:'AZ-TWS-C1001', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'赵丽', volume:37500 },
  { id:'P065', name:'AZ-TWS-C1002', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'陈伟', volume:45000 },
  { id:'P066', name:'AZ-SPK-C1001', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'智能音箱', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'孙强', volume:6000 },
  { id:'P067', name:'AZ-SPK-C1002', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'智能音箱', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'周强', volume:9000 },
  { id:'P068', name:'AZ-SPK-C1003', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'智能音箱', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:12000 },
  { id:'P069', name:'AZ-SWT-C1001', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:7500 },
  { id:'P070', name:'AZ-SWT-C1002', customer:'Amazon', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'杨帆', volume:9000 },
  { id:'P071', name:'MS-SGL-C1001', customer:'Microsoft', bg:'CEP', bu:'CEP-BU1', productLine:'智能眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:1500 },
  { id:'P072', name:'MS-SGL-C1002', customer:'Microsoft', bg:'CEP', bu:'CEP-BU1', productLine:'智能眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'李建国', volume:2250 },
  { id:'P073', name:'MS-MRH-C1001', customer:'Microsoft', bg:'CEP', bu:'CEP-BU1', productLine:'MR头显', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:2000 },
  { id:'P074', name:'MS-MRH-C1002', customer:'Microsoft', bg:'CEP', bu:'CEP-BU1', productLine:'MR头显', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'赵丽', volume:2500 },
  { id:'P075', name:'SS-TWS-C1001', customer:'Samsung', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'陈伟', volume:45000 },
  { id:'P076', name:'SS-TWS-C1002', customer:'Samsung', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'孙强', volume:15000 },
  { id:'P077', name:'SS-TWS-C1003', customer:'Samsung', bg:'CEP', bu:'CEP-BU1', productLine:'真无线耳机', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'周强', volume:22500 },
  { id:'P078', name:'SS-SWT-C1001', customer:'Samsung', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'吴芳', volume:6000 },
  { id:'P079', name:'SS-SWT-C1002', customer:'Samsung', bg:'CEP', bu:'CEP-BU1', productLine:'智能手表', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:7500 },
  { id:'P080', name:'GG-ARG-C2001', customer:'Google', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'杨帆', volume:6000 },
  { id:'P081', name:'GG-ARG-C2002', customer:'Google', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:2000 },
  { id:'P082', name:'GG-VRH-C2001', customer:'Google', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:3750 },
  { id:'P083', name:'GG-VRH-C2002', customer:'Google', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:5000 },
  { id:'P084', name:'AZ-SGL-C2001', customer:'Amazon', bg:'CEP', bu:'CEP-BU2', productLine:'智能眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:3750 },
  { id:'P085', name:'AZ-SGL-C2002', customer:'Amazon', bg:'CEP', bu:'CEP-BU2', productLine:'智能眼镜', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:4500 },
  { id:'P086', name:'MS-ARG-C2001', customer:'Microsoft', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'孙强', volume:2000 },
  { id:'P087', name:'MS-ARG-C2002', customer:'Microsoft', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:true, pm:'周强', volume:3000 },
  { id:'P088', name:'MS-ARG-C2003', customer:'Microsoft', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:4000 },
  { id:'P089', name:'MS-OHP-C2001', customer:'Microsoft', bg:'CEP', bu:'CEP-BU2', productLine:'头戴耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'郑凯', volume:10000 },
  { id:'P090', name:'MS-OHP-C2002', customer:'Microsoft', bg:'CEP', bu:'CEP-BU2', productLine:'头戴耳机', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'杨帆', volume:12000 },
  { id:'P091', name:'MT-VRH-C2001', customer:'Meta', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:2500 },
  { id:'P092', name:'MT-VRH-C2002', customer:'Meta', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'李建国', volume:3750 },
  { id:'P093', name:'MT-VRH-C2003', customer:'Meta', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:5000 },
  { id:'P094', name:'MT-MRH-C2001', customer:'Meta', bg:'CEP', bu:'CEP-BU2', productLine:'MR头显', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:2500 },
  { id:'P095', name:'MT-MRH-C2002', customer:'Meta', bg:'CEP', bu:'CEP-BU2', productLine:'MR头显', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:3000 },
  { id:'P096', name:'SY-VRH-C2001', customer:'Sony', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'孙强', volume:2500 },
  { id:'P097', name:'SY-VRH-C2002', customer:'Sony', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'周强', volume:3750 },
  { id:'P098', name:'SY-VRH-C2003', customer:'Sony', bg:'CEP', bu:'CEP-BU2', productLine:'VR头显', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:5000 },
  { id:'P099', name:'SY-OHP-C2001', customer:'Sony', bg:'CEP', bu:'CEP-BU2', productLine:'头戴耳机', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:true, pm:'郑凯', volume:10000 },
  { id:'P100', name:'SY-OHP-C2002', customer:'Sony', bg:'CEP', bu:'CEP-BU2', productLine:'头戴耳机', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'杨帆', volume:12000 },
  { id:'P101', name:'SS-ARG-C2001', customer:'Samsung', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:2000 },
  { id:'P102', name:'SS-ARG-C2002', customer:'Samsung', bg:'CEP', bu:'CEP-BU2', productLine:'AR眼镜', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'李建国', volume:3000 },
  { id:'P103', name:'HW-MSP-S1001', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:250000 },
  { id:'P104', name:'HW-MSP-S1002', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:312500 },
  { id:'P105', name:'HW-MSP-S1003', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'陈伟', volume:375000 },
  { id:'P106', name:'HW-DYN-S1001', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'动圈扬声器单元', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:75000 },
  { id:'P107', name:'HW-DYN-S1002', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'动圈扬声器单元', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'周强', volume:112500 },
  { id:'P108', name:'HW-DYN-S1003', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'动圈扬声器单元', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'吴芳', volume:150000 },
  { id:'P109', name:'HW-RCV-S1001', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'郑凯', volume:225000 },
  { id:'P110', name:'HW-RCV-S1002', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'杨帆', volume:270000 },
  { id:'P111', name:'HW-RCV-S1003', customer:'华为', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:90000 },
  { id:'P112', name:'HR-MSP-S1001', customer:'荣耀', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'李建国', volume:187500 },
  { id:'P113', name:'HR-MSP-S1002', customer:'荣耀', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:250000 },
  { id:'P114', name:'HR-MSP-S1003', customer:'荣耀', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'赵丽', volume:312500 },
  { id:'P115', name:'HR-RCV-S1001', customer:'荣耀', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:true, pm:'陈伟', volume:270000 },
  { id:'P116', name:'HR-RCV-S1002', customer:'荣耀', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:90000 },
  { id:'P117', name:'MI-MSP-S1001', customer:'小米', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'周强', volume:187500 },
  { id:'P118', name:'MI-MSP-S1002', customer:'小米', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'吴芳', volume:250000 },
  { id:'P119', name:'MI-MSP-S1003', customer:'小米', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'郑凯', volume:312500 },
  { id:'P120', name:'MI-DYN-S1001', customer:'小米', bg:'SAC', bu:'SAC-BU1', productLine:'动圈扬声器单元', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'杨帆', volume:225000 },
  { id:'P121', name:'MI-DYN-S1002', customer:'小米', bg:'SAC', bu:'SAC-BU1', productLine:'动圈扬声器单元', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:75000 },
  { id:'P122', name:'OP-MSP-S1001', customer:'OPPO', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'李建国', volume:187500 },
  { id:'P123', name:'OP-MSP-S1002', customer:'OPPO', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:250000 },
  { id:'P124', name:'OP-MSP-S1003', customer:'OPPO', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'赵丽', volume:312500 },
  { id:'P125', name:'OP-RCV-S1001', customer:'OPPO', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'陈伟', volume:270000 },
  { id:'P126', name:'OP-RCV-S1002', customer:'OPPO', bg:'SAC', bu:'SAC-BU1', productLine:'受话器', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:90000 },
  { id:'P127', name:'VI-MSP-S1001', customer:'vivo', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'周强', volume:187500 },
  { id:'P128', name:'VI-MSP-S1002', customer:'vivo', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'吴芳', volume:250000 },
  { id:'P129', name:'VI-MSP-S1003', customer:'vivo', bg:'SAC', bu:'SAC-BU1', productLine:'微型扬声器', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'郑凯', volume:312500 },
  { id:'P130', name:'GG-MSP-S2001', customer:'Google', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'杨帆', volume:375000 },
  { id:'P131', name:'GG-MSP-S2002', customer:'Google', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'张明远', volume:125000 },
  { id:'P132', name:'GG-MEM-S2001', customer:'Google', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'李建国', volume:225000 },
  { id:'P133', name:'GG-MEM-S2002', customer:'Google', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'刘燕', volume:300000 },
  { id:'P134', name:'GG-MEM-S2003', customer:'Google', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'赵丽', volume:375000 },
  { id:'P135', name:'AZ-MSP-S2001', customer:'Amazon', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'陈伟', volume:375000 },
  { id:'P136', name:'AZ-MSP-S2002', customer:'Amazon', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'孙强', volume:125000 },
  { id:'P137', name:'AZ-MEM-S2001', customer:'Amazon', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:true, pm:'周强', volume:225000 },
  { id:'P138', name:'AZ-MEM-S2002', customer:'Amazon', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'吴芳', volume:300000 },
  { id:'P139', name:'SS-DYN-S2001', customer:'Samsung', bg:'SAC', bu:'SAC-BU2', productLine:'动圈扬声器单元', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'郑凯', volume:187500 },
  { id:'P140', name:'SS-DYN-S2002', customer:'Samsung', bg:'SAC', bu:'SAC-BU2', productLine:'动圈扬声器单元', engStage:'MP', lifecycle:'量产EOL', lifecycleRaw:'EOL', isMajor:false, pm:'杨帆', volume:225000 },
  { id:'P141', name:'SS-MEM-S2001', customer:'Samsung', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:150000 },
  { id:'P142', name:'SS-MEM-S2002', customer:'Samsung', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'李建国', volume:225000 },
  { id:'P143', name:'SS-MEM-S2003', customer:'Samsung', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:300000 },
  { id:'P144', name:'SY-MSP-S2001', customer:'Sony', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'赵丽', volume:312500 },
  { id:'P145', name:'SY-MSP-S2002', customer:'Sony', bg:'SAC', bu:'SAC-BU2', productLine:'微型扬声器', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'陈伟', volume:375000 },
  { id:'P146', name:'SY-BAL-S2001', customer:'Sony', bg:'SAC', bu:'SAC-BU2', productLine:'动铁扬声器单元', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'孙强', volume:40000 },
  { id:'P147', name:'SY-BAL-S2002', customer:'Sony', bg:'SAC', bu:'SAC-BU2', productLine:'动铁扬声器单元', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:true, pm:'周强', volume:60000 },
  { id:'P148', name:'MT-MEM-S2001', customer:'Meta', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'吴芳', volume:300000 },
  { id:'P149', name:'MT-MEM-S2002', customer:'Meta', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'量产爬坡', lifecycleRaw:'Ramp-up', isMajor:false, pm:'郑凯', volume:375000 },
  { id:'P150', name:'MT-MEM-S2003', customer:'Meta', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'PVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'杨帆', volume:450000 },
  { id:'P151', name:'MS-MEM-S2001', customer:'Microsoft', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'MP', lifecycle:'稳定量产', lifecycleRaw:'Mass Production', isMajor:false, pm:'张明远', volume:150000 },
  { id:'P152', name:'MS-MEM-S2002', customer:'Microsoft', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'DVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'李建国', volume:225000 },
  { id:'P153', name:'MS-MEM-S2003', customer:'Microsoft', bg:'SAC', bu:'SAC-BU2', productLine:'MEMS麦克风', engStage:'EVT', lifecycle:'NPI', lifecycleRaw:'NPI', isMajor:false, pm:'刘燕', volume:300000 },
];
const bgColors = { 'A01':'#2a5298', 'CEP':'#e67e22', 'SAC':'#764ba2' };
const buColors = { 'A01-BU1':'#3b82f6', 'A01-BU2':'#60a5fa', 'CEP-BU1':'#f59e0b', 'CEP-BU2':'#fbbf24', 'SAC-BU1':'#8b5cf6', 'SAC-BU2':'#a78bfa' };

const projectFilterOptions = {
  bg: ['A01','CEP','SAC'],
  bu: { 'A01':['BU1','BU2'], 'CEP':['BU1','BU2'], 'SAC':['BU1','BU2'] },
  productLine: [...new Set(projects.map(p=>p.productLine))].sort(),
  customer: [...new Set(projects.map(p=>p.customer))].sort(),
};
